# Copyright (c) 2001-2011 John Graham-Cumming
#
#   This file is part of POPFile
#
#   POPFile is free software; you can redistribute it and/or modify it
#   under the terms of version 2 of the GNU General Public License as
#   published by the Free Software Foundation.
#
#   POPFile is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with POPFile; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

# Identify the language and character set used for the interface
LanguageCode                            he
LanguageCharset                         UTF-8
LanguageDirection                       rtl

# This is used to get the appropriate subdirectory for the manual
ManualLanguage                          en

# Common words that are used on their own all over the interface
Apply                                   שמור
On                                      פעיל
Off                                     כבוי
TurnOn                                  הפעל
TurnOff                                 כבה
Add                                     הוסף
Remove                                  הסר
Previous                                קודם
Next                                    הבא
From                                    נתקבל מ
Subject                                 נושא
Classification                          סיווג
Reclassify                              סיווג מחדש
Undo                                    חזרה לקודם
Close                                   סגור
Find                                    מצא
Filter                                  סינון
Yes                                     כן
No                                      לא
ChangeToYes                             שנה ל 'כן'
ChangeToNo                              שנה ל 'לא'
Bucket                                  מצבור
Magnet                                  מגנט
Delete                                  מחק
Create                                  הוסף
To                                      נשלח ל
Total                                   סך כולל
Rename                                  שינוי שם
Frequency                               תדירות
Probability                             הסתברות
Score                                   ציון
Lookup                                  חפש
Cc                                      CC
Count                                   מספר
QuickMagnets                            מגנטים מהירים
Refresh                                 רענון התצוגה
Scores                                  ציונים
Update                                  עידכון
View_Title                              פרטי הודעה ספציפית
Windows_TrayIcon                        הצג איקון של POPfile במגש חלונות
Word                                    מילה

# The header and footer that appear on every UI page
Header_Title                            לוח הבקרה של POPFile
Header_Shutdown                         כיבוי תוכנת POPFile
Header_History                          היסטוריה
Header_Buckets                          מצבורים
Header_Configuration                    הגדרות
Header_Advanced                         הגדרות מתקדמות
Header_Security                         אבטחה
Header_Magnets                          מגנטים

Footer_HomePage                         דף הבית של POPFile
Footer_Manual                           הוראות הפעלה
Footer_Forums                           פורומים
Footer_FeedMe                           תרומה
Footer_RequestFeature                   בקש חידוש\שינוי
Footer_MailingList                      רשימת Email

Configuration_Error1                    התו המפריד בין מיליה צריך להיות תו יחיד
Configuration_Error2                    הגדרת השער של ממשק המשתמש צריכה להיות מספר בין 1 ל 65535
Configuration_Error3                    הגדרת השער של 'POP3' צריכה להיות מספר בין 1 ל 65535
Configuration_Error4                    גודל העמוד צריך להיות מספר בין 1 ל 1000 
Configuration_Error5                    מספר הימים שהתוכנה תשמור היסטוריה צריך להיות בין 1 ל 366
Configuration_Error6                    מגבלת הזמן להתחברות TCP צריכה להיות בין 10 ל 1800 מילישניות
Configuration_POP3Port                  POP3 שער ההאזנה לפרוטוקול 
Configuration_POP3Update                הגדרת השער שונתה ל %s. השינוי יכנס לתוקף  רק אחרי איתחול POPFile מחדש
Configuration_UI                        שער החיבור של ממשק המשתמש
Configuration_UIUpdate                  הגדרת השער של ממשק המשתמש שונתה ל %s. השינוי יכנס לתוקף  רק אחרי איתחול POPFile מחדש
Configuration_History                   מספר הודעות שיראו בעמוד אחד
Configuration_HistoryUpdate             מספר הודעות שיראו בעמוד אחד עודכן ל %s
Configuration_Days                      מספר הימים שהתוכנה תשמור היסטוריה
Configuration_DaysUpdate                מספר הימים שהתוכנה תשמור היסטוריה עודכן ל %s
Configuration_UserInterface             ממשק המשתמש
Configuration_Skins                     מראה
Configuration_SkinsChoose               בחר מראה
Configuration_Language                  שפה
Configuration_LanguageChoose            בחר שפה
Configuration_ListenPorts               שערי ההאזנה
Configuration_HistoryView               היסטוריה
Configuration_TCPTimeout                מגבלת זמן התחברות TCP
Configuration_TCPTimeoutSecs            מגבלת זמן התחברות TCP בשניות
Configuration_TCPTimeoutUpdate          מגבלת זמן התחברות TCP שונתה ל %s
Configuration_ClassificationInsertion   הוספת טקסט להודעות
Configuration_SubjectLine               שינוי שורת שנושא של הודעות
Configuration_XTCInsertion              הוספת X-Text-Classification לראש הודעה
Configuration_XPLInsertion              הוספת X-POPFile-Link Header לגוף ההודעה
Configuration_Logging                   רשומת יומן
Configuration_None                      כלום
Configuration_ToScreen                  למסך
Configuration_ToFile                    לקובץ
Configuration_ToScreenFile              למסך ולקובץ
Configuration_LoggerOutput              פלט 
Configuration_GeneralSkins              מראות
Configuration_SmallSkins                מראות קטנים
Configuration_TinySkins                 מראות קטנטנים
Configuration_CurrentLogFile            &lt;קובץ היומן העכשוי&gt;
Configuration_Error7                    מספר השער של XML RPC המוגן צרין להיות מספר בין 1 ל 65535
Configuration_NNTPPort                  שער האזנה לפרוטוקול NNTP
Configuration_NNTPSeparator             תו הפרדת ערכי NNTP host:port:user
Configuration_NNTPSepUpdate             תו ההפרדה לערכי NNTP עודכן ל %s
Configuration_NNTPUpdate                שער NNTP עודכן ל %s. השינוי יכנס לתוקף רק לאחר איתחול התוכנה מחדש.
Configuration_POP3Separator             תו הפרדת ערכי POP3 host:port:user
Configuration_POP3SepUpdate             תו ההפרדה של ערכי POP3 עודכן ל %s
Configuration_SMTPPort                  שער האזנה לפרוטוקול SMTP
Configuration_SMTPUpdate                שער האזנה לפרוטוקול SMTP עודכן ל %s. השינוי יכנס לתוקף רק לאחר איתחול התוכנה מחדש.
Configuration_XMLRPCPort                שער האזנה לפרוטוקול XML-RPC
Configuration_XMLRPCUpdate              שער האזנה לפרוטוקול XML-RPC עודכן ל %s. השינוי יכנס לתוקף רק לאחר איתחול התוכנה מחדש.


Advanced_Error1                         '%s' כבר נמצאת ברשימת המילים להתעלמות
Advanced_Error2                         מילים ברשימת ההתעלמות חיבות להכיל אותיות, מספרים והתוים ., _, - או @ בלבד
Advanced_Error3                         '%s' נשמרה ברשימת המילים להתעלמות 
Advanced_Error4                         '%s' אינה ברשימת המילים להתעלמות
Advanced_Error5                         '%s'  הוסרה מרשימת המילים להתעלמות
Advanced_StopWords                      מילים שמהן התוכנה מתעלמת
Advanced_Message1                       התוכנה התעלמה ממלים נפוצות אלו:
Advanced_AddWord                        הוסף מילה
Advanced_RemoveWord                     הסר מילה
Advanced_AllParameters                  כל הפרמטרים של POPFile
Advanced_Parameter                      פרמטר
Advanced_Value                          ערך
Advanced_Warning                        רשימה זו מפרטת את כל הפרמטרים של התוכנה. למשתמשים מתקדמים בלבד: ניתן לשנות כל ערך וללחוץ על כפתור 'עדכון'

History_Filter                          &nbsp;)תצוגת מצבור <font color="%s">%s</font> בלבד(
History_FilterBy                        סינון לפי
History_Search                          &nbsp;) חיפוש '%s' בוצע ב 'נשלח מ' ונושא ההודעה(
History_Title                           הודעות אחרונות
History_Jump                            גישה ישירה להודעה
History_ShowAll                         הראה את הכל
History_ShouldBe                        צריך להיות
History_NoFrom                          שורת 'נשלח מ' חסרה
History_NoSubject                       שורת הנושא חסרהno subject line
History_ClassifyAs                      סווג כ
History_MagnetUsed                      מגנט שומש
History_ChangedTo                       שנה ל <font color="%s">%s</font>
History_Already                         כבר סווג כ <font color="%s">%s</font>
History_RemoveAll                       הסר את כל אלה שנבחרו 
History_RemovePage                      הסר את כל אלה שבעמוד
History_Remove                          להסרת פריטים מההיסטוריה
History_SearchMessage                   חיפוש ב 'נשלח מ' ושורת הנושא
History_NoMessages                      לא נמצאו הודעות
History_ShowMagnet                      הודעות ממוגנטות
History_Magnet                          &nbsp;(פריטים שסווגו ע"י מגנט בלבד)
History_ResetSearch                     איפוס חיפוש 
History_MagnetBecause                   <b>ע"י מגנט</b><p>סיווג ל <font color="%s">%s</font>
History_NoMagnet                        &nbsp;)רק הודעות שסווגו ללא מגנט מוצגות)
History_ShowNoMagnet                    בלתי ממוגנטים

Password_Title                          סיסמא
Password_Enter                          הכנס סיסמא
Password_Go                             קדימה!
Password_Error1                         סיסמא שגויה

Security_Error1                         מספר השער המוגן צרין להיות מספר בין 1 ל 65535
Security_Stealth                        הרשאות חיבור ממחשבים אחרים
Security_NoStealthMode                  לא (פעולה חסויה)
Security_ExplainStats                   כשאפשרות זו נבחרת, POPFile מתחברת אחת ליום לשרת getpopfile.org ומוסרת 3 פרטים: bc (מספר המצבורים שיש לך), mc (מספר ההודעות שהתוכנה סיווגה), ac (מספר טעויות הסיווג שהתוכנה ביצעה). נתונים אלה נשמרים בקובץ, ואני אשתמש בהם לפירסום סטטיסטיקה כוללנית על איך אנשים משתמשים בתוכנה ורמת הדיוק שלה. הקבצים נשמרים כ5 ימים בשרת ונמחקים לאחר מכן. מידע המקשר בין כתובת ה IP שלך לבין הסטטיסטיקה אינו נשמר או מפורסם.
Security_ExplainUpdate                  כשאפשרות זו נבחרת, POPFile מתחברת אחת ליום לשרת getpopfile.org ומוסרת 3 פרטים: ma (מספר הגירסה הראשי של POPFile המותקנת במחשבך), ma (מספר הגירסה המשני של POPFile המותקנת במחשבך), bn (גירסת הקומפילציה של POPFile המותקנת במחשבך).POPFile תקבל משוב מהשרת בצורת איקון גרפי המראה אם קיימת גירסה חדשה שתוכל להתקין.  3 הנתונים נשמרים בקובץ בשרת. הקבצים נשמרים כ5 ימים בשרת ונמחקים לאחר מכן. מידע המקשר בין כתובת ה IP שלך לבין  שלושת הפריטים אינו נשמר או מפורסם.
Security_PasswordTitle                  סיסמא לממשק המשתמש
Security_Password                       סיסמא
Security_PasswordUpdate                 הסיסמא עודכנה ל %s
Security_AUTHTitle                      סכמת Secure Password Authentication/AUTH
Security_SecureServer                   שרת מאובטח
Security_SecureServerUpdate             השרת המאובטח עודכן ל %s . השינוי יכנס לתוקף רק אחרי שתאתחל את POPFile מחדש.
Security_SecurePort                     שער מאובטח
Security_SecurePortUpdate               השער עודכן ל %s. השינוי יכנס לתוקף רק לאחר איתחול התוכנה מחדש
Security_POP3                           הרשאה לחיבור POP3 ממחשבים אחרים (מצריך איתחול התוכנה למתן תוקף)
Security_UI                             הרשאה לחיבור HTTP (ממשק המשתמש) ממחשבים אחרים (מצריך איתחול התוכנה למתן תוקף) 
Security_UpdateTitle                    בדיקת עדכון תוכנה אוטומטית
Security_Update                         בצע בדיקה יומית לעדכון התוכנה
Security_StatsTitle                     דיווח סטטיסטי
Security_Stats                          שלח דיווח סטטיסטי יומי
Security_SMTP                           הרשאה לחיבור SMTP ממחשבים אחרים (מצריך איתחול התוכנה למתן תוקף)
Security_SMTPServer                     שרת SMTP
Security_SMTPPort                       שער SMTP
Security_NNTP                           הרשאה לחיבור NNTP ממחשבים אחרים (מצריך איתחול התוכנה למתן תוקף)
Security_SMTPPortUpdate                 שער שרשרת SMTP עודכן ל %s. השינוי יכנס לתוקף רק לאחר איתחול התוכנה מחדש
Security_SMTPServerUpdate               שרת השרשרת ל SMTP עודכן ל %s. השינוי יכנס לתוקף רק לאחר איתחול התוכנה מחדש
Security_XMLRPC                         הרשאה לחיבור XML-RPC ממחשבים אחרים (מצריך איתחול התוכנה למתן תוקף)

Magnet_Error1                           מגנט '%s' כבר קיים במצבור '%s'
Magnet_Error2                           המגנט החדש '%s' מתנגש עם מגנט קיים '%s' במצבור '%s' ועלול לגרום לתוצאות דו משמעיות, ועל כן לא נשמר.
Magnet_Error3                           נקבע מגנט חדש '%s' במצבור '%s'
Magnet_CurrentMagnets                   מגנעים קיימים
Magnet_Message1                         מגנטים אלו יגרמו לסיווג הודעות אל מצבור '%s' תמיד.
Magnet_CreateNew                        קבע מגנט חדש
Magnet_Explanation                      קיימים 3 סוגי מגנטים:  <ul><li><b>'נשלח מ' כתובת או שם:</b> לדוגמא: <u>john@company.com</u> למגנוט כתובת ספציפית, <br /><u>company.com</u> למגנוט כל כתובת מהחברה <u>company.com</u>, <br /><u>John Doe</u> למיגנוט שם מסוים,<br /> <u>John</u> למגנוט כל מי ששמו <u>John</u></li><li><b>לשם או כתובת:</b>כמו 'נשלח מ' אבל בשדה 'נשלח ל' בהודעה</li> <li><b>מילות נושא: </b> לדוגמא: שלום ימגנט כל הודעה בה מופיעה המילה שלום בנושא ההודעה</li></ul>
Magnet_MagnetType                       סוג המגנט
Magnet_Value                            תוכן המגנט
Magnet_Always                           סווג תמיד אל תוך מצבור
Magnet_Jump                             קישור לדף המגנטים

Bucket_Error1                           שם מצבור יכול להכיל אותיות לועזיות בלבד ואת התווים - ו _
Bucket_Error2                           מצבור בשם '%s' כבר קיים
Bucket_Error3                           מצבור בשם '%s' נוצר ונשמר
Bucket_Error4                           יש להזין מילה כלשהי
Bucket_Error5                           שם המצבור '%s' שונה ל '%s'
Bucket_Error6                           מצבור '%s' נמחק
Bucket_Title                            
Bucket_BucketName                       שם מצבור
Bucket_WordCount                        מספר מילים
Bucket_WordCounts                       מספרי מילים
Bucket_UniqueWords                      מילים ייחודיות
Bucket_SubjectModification              שינוי שורת נושא
Bucket_ChangeColor                      שנה צבע
Bucket_NotEnoughData                    מידע חסר
Bucket_ClassificationAccuracy           מידת דיוק הסיווג
Bucket_EmailsClassified                 הודעות שסווגו
Bucket_EmailsClassifiedUpper            הודעות שסווגו
Bucket_ClassificationErrors             טעויות בסיווג
Bucket_Accuracy                         מידת הדיוק
Bucket_ClassificationCount              מספר סיווגים
Bucket_ResetStatistics                  איפוס סטטיסטיקה
Bucket_LastReset                        איפוס אחרון
Bucket_CurrentColor                     '%s' צבע כעת '%s'
Bucket_SetColorTo                       קבע צבע '%s' ל '%s'
Bucket_Maintenance                      תחזוקה
Bucket_CreateBucket                     הוסף מצבור בשם
Bucket_DeleteBucket                     מחק מצבור  זה
Bucket_RenameBucket                     שנה שם מצבור בשם 
Bucket_Lookup                           מצא במצבור
Bucket_LookupMessage                    מצא מילים במצבורים
Bucket_LookupMessage2                   תוצאות חיפוש של: 
Bucket_LookupMostLikely                 <b>%s</b> ימצא קרוב לודאי במצבור <font color="%s">%s</font>
Bucket_DoesNotAppear                    <p><b>%s</b> לא מופיע באף אחד מן המצבורים
Bucket_DisabledGlobally                 נוטרל כליל
Bucket_To                               ל:
Bucket_Quarantine                       בידוד
Bucket_ClassificationFN                 סיווג חיובי מוטעה
Bucket_ClassificationFP                 סיווג שלילי מוטעה

SingleBucket_Title                      פירוט %s
SingleBucket_WordCount                  מספר המילים במצבור
SingleBucket_TotalWordCount             מספר המילים כולל
SingleBucket_Percentage                 אחוז מסך כולל
SingleBucket_WordTable                  טבלת המילים ב '%s'
SingleBucket_Message1                   הסיווג השתמש נמילים המסומנות ב '*'. לחץ על מילה בכדי לראות את ההסתברות שלה בכל המצבורים.
SingleBucket_Unique                     ייחודייות %s
SingleBucket_ClearBucket                מחיקת כל המילים במצבור זה

Session_Title                           פג תוקף החיבור ל POPFile
Session_Error                           תוקף החיבור שלך ל POPFile פג. הסיבה עשויה להיות שהדפדפן נשאר פתוח, אך התוכנה אותחלה )כובתה שוגרה מחדש(. לחץ על אחד מהקישורים למעלה כדי להמשיך את השימוש.



Header_MenuSummary                      This table is the navigation menu which allows access to each of the different pages of the control center.
History_MainTableSummary                This table shows the sender and subject of recently received messages and allows them to be reviewed and reclassified.  Clicking on the subject line will show the full message text, along with information about why it was classified as it was.  The 'needs to be' column allows you to specify which bucket the message belongs in, or to undo that change.  The 'Delete' column allows you to delete specific messages from the history if you don't need them anymore.
History_OpenMessageSummary              This table contains the full text of an email message, with the words that are used for classification highlighted according to the bucket that was most relevant for each.
Bucket_MainTableSummary                 This table provides an overview of the classification buckets.  Each row shows the bucket name, the word count total for that bucket, the actual number of individual words in each bucket, whether the email's subject line will be modified when it gets classified to that bucket, whether to quarantine the messages received in that bucket, and a table to pick the color used in displaying anything related to that bucket in the control center.
Bucket_StatisticsTableSummary           This table provides three sets of statistics on the overall performance of POPFile.  The first is how accurate its classification is, the second is how many emails have been classified, and to which מצבורים, and the third is how many words are in each bucket, and what their relative percentages are.
Bucket_MaintenanceTableSummary          This table contains forms that allow you to create, delete or rename buckets, and to lookup a word in all of the buckets to see its relative probabilities.
Bucket_AccuracyChartSummary             This table graphically represents the accuracy of the email classification.
Bucket_BarChartSummary                  This table graphically represents a percentage allocation for each of the different buckets.  It is used for both number of הודעות סווגו, and total word counts.
Bucket_LookupResultsSummary             This table shows the probabilities associated with any given word of the corpus.  For each bucket, it shows the frequency that that word occurs, the probability that it will occur in that bucket, and the overall effect on the score of the bucket if that word exists in an email.
Bucket_WordListTableSummary             This table provides a listing of all the words for a particular bucket, organized by common first letter for each row.
Magnet_MainTableSummary                 This table shows the list of magnets that are used to automatically classify email according to fixed rules.  Each row shows how the magnet is defined, what bucket it is intended for, and a button to delete the magnet.
Configuration_MainTableSummary          This table contains a number of forms to allow you to control the configuration of POPFile.
Configuration_InsertionTableSummary     This table contains buttons that determine whether or not certain modifications are made to the headers or subject line of the email before it is passed on to the email client.
Security_MainTableSummary               This table provides sets of controls that affect the security of the overall configuration of POPFile, whether it needs automatically check for updates to the program, and whether statistics about POPFile's performance needs be sent to the central datastore of the program's author for general information.
Advanced_MainTableSummary               This table provides a list of words that POPFile ignores when classifying email due to their relative frequency in email in general.  They are organized per row according to the first letter of the words.
