# Copyright (c) 2001-2011 John Graham-Cumming
#
#   This file is part of POPFile
#
#   POPFile is free software; you can redistribute it and/or modify it
#   under the terms of version 2 of the GNU General Public License as
#   published by the Free Software Foundation.
#
#   POPFile is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with POPFile; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# Translation by          Myroslav Opyr <myroslav@zope.net.ua>

# Переклад зд╕йснювався зг╕дно терм╕нолог╕╖, що опрацьову╓ться 
# ╕н╕ц╕ативно групою перекладач╕в з http://linux.org.ua/
# Сей переклад виконав Мирослав Опир <myroslav@zope.net.ua>.
# Зауваження та побажання прошу подавати на мою адресу, або
# тут: http://zope.net.ua/POPFile

# Identify the language and character set used for the interface
LanguageCode                            uk
LanguageCharset                         koi8-u
LanguageDirection                       ltr

# This is used to get the appropriate subdirectory for the manual
ManualLanguage                          en

# Common words that are used on their own all over the interface
Apply                                   Застосувати
On                                      Вв╕мк.
Off                                     Вимк.
TurnOn                                  Вв╕мкнути
TurnOff                                 Вимкнути
Add                                     Додати
Remove                                  Вилучити
Previous                                Попередн╕
Next                                    Наступн╕
From                                    В╕д
Subject                                 Тема 
Cc                                      Коп╕я 
Classification                          Класиф╕кац╕я
Reclassify                              Зм╕нити
Probability                             ╤мов╕рн╕сть
Scores                                  Бали
QuickMagnets                            Швидк╕ магн╕ти
Undo                                    Повернути
Close                                   Закрити
Find                                    Знайти
Filter                                  В╕дф╕льтрувати
Yes                                     Так
No                                      Н╕
ChangeToYes                             Зм╕нити на "Так"
ChangeToNo                              Зм╕нити на "Н╕"
Bucket                                  Категор╕я
Magnet                                  Магн╕т
Delete                                  Знищити
Create                                  Створити
To                                      До
Total                                   Загалом
Rename                                  Перейменувати
Frequency                               Частота
Probability                             ╤мов╕рн╕сть
Score                                   Бали
Lookup                                  П╕дглянути
Word                                    Слово
Count                                   К╕льк╕сть
Update                                  Виправити
Refresh                                 Поновити

# The header and footer that appear on every UI page
Header_Title                            Центр управл╕ння POPFile
Header_Shutdown                         Заглушити POPFile
Header_History                          ╤стор╕я
Header_Buckets                          Категор╕╖
Header_Configuration                    Настройка
Header_Advanced                         Додатково
Header_Security                         Безпека
Header_Magnets                          Магн╕ти

Footer_HomePage                         Домашня стор╕нка POPFile
Footer_Manual                           Документац╕я
Footer_Forums                           Форуми
Footer_FeedMe                           Нагодуйте мене!
Footer_RequestFeature                   ╢ ╕дея? Замовляйте
Footer_MailingList                      Список розсилки

Configuration_Error1                    Символ розд╕льник повинен бути один
Configuration_Error2                    Порт ╕нтерфейсу користувача повинен бути числом в╕д 1 до 65535
Configuration_Error3                    Порт POP3 повинен бути числом в╕д 1 до 65535
Configuration_Error4                    Розм╕р стор╕нки повинен бути числом в╕д 1 до 1000
Configuration_Error5                    К╕льк╕сть дн╕в в ╕стор╕╖ повинна бути числом в╕д 1 до 366
Configuration_Error6                    Обмеження по затримц╕ TCP повинно бути числом в╕д 10 до 1800
Configuration_Error7                    Порт XML-RPC повинен бути числом в╕д 1 до 65535
Configuration_POP3Port                  Порт POP3
Configuration_POP3Update                Зм╕нено POP3 порт на %s; ця зм╕на не буде д╕йсною поки ви не рестарту╓те POPFile
Configuration_XMLRPCUpdate              Зм╕нено XML-RPC порт на %s; ця зм╕на не буде д╕йсною поки ви не рестарту╓те POPFile
Configuration_XMLRPCPort                Порт XML-RPC
Configuration_SMTPPort                  Порт SMTP
Configuration_SMTPUpdate                Зм╕нено SMTP порт на %s; ця зм╕на не буде д╕йсною поки ви не рестарту╓те POPFile
Configuration_NNTPPort                  Порт NNTP
Configuration_NNTPUpdate                Зм╕нено NNTP порт на %s; ця зм╕на не буде д╕йсною поки ви не рестарту╓те POPFile
Configuration_POP3Separator             Символ розд╕льник POP3 (гост:порт:користувач)
Configuration_NNTPSeparator             Символ розд╕льник NNTP (гост:порт:користувач)
Configuration_POP3SepUpdate             Зм╕нено розд╕льник POP3 на %s
Configuration_NNTPSepUpdate             Зм╕нено розд╕льник NNTP на %s
Configuration_UI                        Веб порт ╕нтерфейсу користувача
Configuration_UIUpdate                  Зм╕нено веб порт ╕нтерфейсу користувача на %s; ця зм╕на не буде д╕йсною поки ви не рестарту╓те POPFile
Configuration_History                   К╕льк╕сть лист╕в на стор╕нц╕
Configuration_HistoryUpdate             Зм╕нено к╕льк╕сть лист╕в на стор╕нц╕ на %s
Configuration_Days                      ╤стор╕ю збер╕гати на протяз╕ ст╕лькох дн╕в
Configuration_DaysUpdate                Зм╕нено к╕льк╕сть дн╕в на %s, на протяз╕ яких збер╕га╓ться ╕стор╕я
Configuration_UserInterface             ╤нтерфейс користувача
Configuration_Skins                     Вигляд
Configuration_SkinsChoose               Вибер╕ть вигляд
Configuration_Language                  Мова
Configuration_LanguageChoose            Вибер╕ть мову
Configuration_ListenPorts               Слухати на портах
Configuration_HistoryView               Вигляд ╕стор╕╖
Configuration_TCPTimeout                Обмеження по затримц╕ TCP
Configuration_TCPTimeoutSecs            Обмеження по затримц╕ TCP в секундах
Configuration_TCPTimeoutUpdate          Оновлено TCP затримку до %s
Configuration_ClassificationInsertion   Вставляння класиф╕кац╕╖
Configuration_SubjectLine               Модиф╕кац╕я теми
Configuration_XTCInsertion              Вставляти X-Text-Classification
Configuration_XPLInsertion              Вставляти X-POPFile-Link
Configuration_Logging                   Зв╕тування
Configuration_None                      нема
Configuration_ToScreen                  на екран
Configuration_ToFile                    в файл
Configuration_ToScreenFile              на екран ╕ в файл
Configuration_LoggerOutput              Вив╕д зв╕ту
Configuration_GeneralSkins              Звичайн╕
Configuration_SmallSkins                Мал╕
Configuration_TinySkins                 Тенд╕тн╕
Configuration_CurrentLogFile            &laquo;поточний протокол&raquo;

Advanced_Error1                         '%s' уже в списку сл╕в
Advanced_Error2                         Слова, що ╕гноруються можуть т╕льки м╕стити букви, цифри, символи ., _, -, чи @
Advanced_Error3                         '%s' додано до списку
Advanced_Error4                         '%s' нема╓ в списку
Advanced_Error5                         '%s' вилучено з╕ списку
Advanced_StopWords                      Список сл╕в, що ╕гноруються
Advanced_Message1                       Ц╕ слова ╕гноруються у вс╕х класиф╕кац╕ях, так як зустр╕чаються дуже часто.
Advanced_AddWord                        Додати слово
Advanced_RemoveWord                     Вилучити слово

History_Filter                          &nbsp;(т╕льки показуючи категор╕ю <font color=%s>%s</font>)
History_FilterBy                        Ф╕льтр по
History_Search                          &nbsp;(пошукавши за темою %s)
History_Title                           Останн╕ пов╕домлення
History_Jump                            Перейти до пов╕домлення
History_ShowAll                         Показати ус╕
History_ShouldBe                        Ма╓ бути
History_NoFrom                          нема╓ рядка В╕д
History_NoSubject                       нема рядка Теми
History_ClassifyAs                      Прокласиф╕куй як
History_MagnetUsed                      Використано магн╕т
History_MagnetBecause                   <b>Використано Магн╕т</b><p>Прокласиф╕ковано як <font color="%s">%s</font> бо зад╕яно магн╕т %s </p>
History_ChangedTo                       Зм╕нено на <font color=%s>%s
History_Already                         Уже зм╕нено на <font color=%s>%s</font>
History_RemoveAll                       Вилучити вс╕
History_RemovePage                      Вилучити стор╕нку
History_Remove                          Щоб вилучити елементи з ╕стор╕╖ клацн╕ть
History_SearchMessage                   Пошук по В╕д/Тема
History_NoMessages                      Нема╓ пов╕домлень
History_ShowMagnet                      Намагн╕чен╕
History_ShowNoMagnet                    Ненамагн╕чен╕
History_Magnet                          &nbsp;(т╕льки пов╕домлення притягнут╕ магн╕тами)
History_NoMagnet                        &nbsp;(т╕льки пов╕домлення непритягнут╕ магн╕тами)
History_ResetSearch                     Скинути

Password_Title                          Пароль
Password_Enter                          Введ╕ть пароль
Password_Go                             Вперед!
Password_Error1                         Неправильний пароль

Security_Error1                         Безпечний порт повинен бути числом м╕ж 1 та 65535
Security_Stealth                        Невидимий режим/робота сервера
Security_NoStealthMode                  Н╕ (Невидимий режим)
Security_ExplainStats                   (Якщо це вв╕мкнуто, то POPFile надсила╓ раз в день наступн╕ три значенн╕ скрипту на getpopfile.org: bc (загальна к╕льк╕сть категор╕й, яку ма╓те), mc (загальну к╕льк╕сть пов╕домлень що прокласиф╕кував POPFile) та ec (загальна к╕льк╕сть помилок класиф╕кац╕╖).  Вони збер╕гаються в файл╕ ╕ я використовую ╖х щоб опубл╕кувати деяку статистику про те, як люди використовують POPFile ╕ наск╕льки добре в╕н для них працю╓.  М╕й веб сервер збер╕га╓ сво╖ файли зв╕т╕в коло 5 дн╕в ╕ тод╕ ╖х стира╓ться; я не збер╕гаю будь якого зв'язку м╕ж статистикою та ╕ндив╕дуальними IP адресами.)
Security_ExplainUpdate                  (Якщо це вв╕мкнуто, то POPFile надсила╓ раз в день наступн╕ три значенн╕ скрипту на getpopfile.org: ma (основна верс╕я вашого встановленого POPFile), mi (вторинна верс╕я вашого встановленого POPFile) та bn (номер побудови вашого встановленого POPFile).  POPFile отриму╓ в╕дпов╕дь у форм╕ граф╕ки що з'явля╓ться згори стор╕нки якщо наявна нова верс╕я.  М╕й веб сервер збер╕га╓ сво╖ файли зв╕т╕в коло 5 дн╕в ╕ тод╕ ╖х стира╓ться; я не збер╕гаю будь якого зв'язку м╕ж перев╕ркою оновлень та ╕ндив╕дуальними IP адресами.)
Security_PasswordTitle                  Пароль ╕нтерфейсу користувача
Security_Password                       Пароль
Security_PasswordUpdate                 Пароль зм╕нено для %s
Security_AUTHTitle                      Безпечна автентиф╕кац╕я паролем/AUTH
Security_SecureServer                   Безпечний сервер
Security_SecureServerUpdate             Зм╕нено безпечний сервер на %s; ця зм╕на не буде д╕йсною поки ви не рестарту╓те POPFile
Security_SecurePort                     Безпечний порт
Security_SecurePortUpdate               Зм╕нено порт на %s; ця зм╕на не буде д╕йсною поки ви не рестарту╓те POPFile
Security_SMTPServer                     Ланцюговий сервер SMTP<br/><small>(myroslav@zope.net.ua: перев╕рити переклад)</small>
Security_SMTPServerUpdate               Зм╕нено ланцюговий сервер SMTP на %s; ця зм╕на не буде д╕йсною поки ви не рестарту╓те POPFile<br/><small>(myroslav@zope.net.ua: перев╕рити переклад)</small>
Security_SMTPPort                       Ланцюговий порт SMTP<br/><small>(myroslav@zope.net.ua: перев╕рити переклад)</small>
Security_SMTPPortUpdate                 Зм╕нено ланцюговий порт SMTP на %s; ця зм╕на не буде д╕йсною поки ви не рестарту╓те POPFile<br/><small>(myroslav@zope.net.ua: перев╕рити переклад)</small>
Security_POP3                           Приймати POP3 п╕д'╓днання з в╕ддалених машин (вимага╓ рестарту POPFile)
Security_SMTP                           Приймати SMTP п╕д'╓днання з в╕ддалених машин (вимага╓ рестарту POPFile)
Security_NNTP                           Приймати NNTP п╕д'╓днання з в╕ддалених машин (вимага╓ рестарту POPFile)
Security_UI                             Приймати HTTP (╕нтерфейс користувача) п╕д'╓днання в╕д в╕ддалених машин
Security_XMLRPC                         Приймати XML-RPC п╕д'╓днання з в╕ддалених машин (вимага╓ рестарту POPFile)
Security_UpdateTitle                    Автоматична перев╕рка оновлень
Security_Update                         Щоденно перев╕ряти за оновленнями POPFile
Security_StatsTitle                     Зв╕тування статистики
Security_Stats                          В╕дсилати щоденно статистику назад до Джона

Magnet_Error1                           Магн╕т '%s' уже ╕сну╓ в категор╕╖ '%s'
Magnet_Error2                           Новий магн╕т '%s' конфл╕кту╓ з магн╕том '%s' в категор╕╖ '%s' ╕ може спричинити неоднозначн╕ результати.  Нового магн╕ту НЕ додано.
Magnet_Error3                           Створено новий магн╕т '%s' в категор╕╖ '%s'
Magnet_CurrentMagnets                   Наявн╕ магн╕ти
Magnet_Message1                         Наступн╕ магн╕ти заставляють пошту завжди бути класиф╕кованою у вказану категор╕ю.
Magnet_CreateNew                        Створити новий магн╕т
Magnet_Explanation                      Можлив╕ три види магн╕т╕в: <ul><li><b>Адреса або ╕м'я В╕д:</b> Наприклад: john@company.com щоб притягнути певну адресу, <br>company.com щоб притягнути ус╕х, хто посила╓ з company.com, <br>John Doe щоб притягнути певну особу, John щоб притягнути ус╕х Джон╕в<li><b>Адреса або ╕м'я До:</b> Под╕бно до магн╕ту В╕д: але щодо адреси До: З листа<li><b>Слова з Теми:</b> Наприклад: hello щоб притягнути ус╕ слова з hello в тем╕</ul>
Magnet_MagnetType                       Тип магн╕ту
Magnet_Value                            Значення
Magnet_Always                           Завжди п╕де в категор╕ю
Magnet_Jump                             Перескочити на стор╕нку магн╕т╕в

Bucket_Error1                           ╤мена категор╕й можуть м╕стити т╕льки мал╕ л╕тери в╕д a до z та - ╕ _
Bucket_Error2                           Категор╕я з назвою %s уже ╕сну╓
Bucket_Error3                           Створено категор╕ю з назвою %s
Bucket_Error4                           Введ╕ть будь-ласка непорожн╓ слово
Bucket_Error5                           Перейменовано категор╕ю %s на %s
Bucket_Error6                           Знищено категор╕ю %s
Bucket_Title                            Зв╕т
Bucket_BucketName                       Категор╕я
Bucket_WordCount                        К╕льк╕сть сл╕в
Bucket_WordCounts                       К╕лькост╕ сл╕в
Bucket_UniqueWords                      Ун╕кальн╕
Bucket_SubjectModification              Зм╕нювати тему
Bucket_ChangeColor                      Кол╕р
Bucket_NotEnoughData                    Недостатньо даних
Bucket_ClassificationAccuracy           Точн╕сть класиф╕кац╕╖
Bucket_EmailsClassified                 Прокласиф╕ковано лист╕в
Bucket_EmailsClassifiedUpper            Прокласиф╕ковано лист╕в
Bucket_ClassificationErrors             Помилок класиф╕кац╕╖
Bucket_Accuracy                         Точн╕сть
Bucket_ClassificationCount              К╕льк╕сть
Bucket_ClassificationFP                 Неправильн╕ Попадання
Bucket_ClassificationFN                 Неправильн╕ Промахи
Bucket_ResetStatistics                  Скинути статистику
Bucket_LastReset                        Востанн╓ скинуто
Bucket_CurrentColor                     %s поточний кол╕р %s
Bucket_SetColorTo                       Встановити %s кол╕р для %s
Bucket_Maintenance                      Управл╕ння категор╕ями
Bucket_CreateBucket                     Створити категор╕ю з ╕менем
Bucket_DeleteBucket                     Знищити категор╕ю ╕меновану
Bucket_RenameBucket                     Перейменувати категор╕ю ╕меновану
Bucket_Lookup                           П╕дглянути
Bucket_LookupMessage                    Знайти слово в категор╕ях
Bucket_LookupMessage2                   Результат пошуку
Bucket_LookupMostLikely                 <b>%s</b> най╕мов╕рн╕ше появля╓ться в <font color=%s>%s</font>
Bucket_DoesNotAppear                    <p><b>%s</b> не з'явля╓ться в жодн╕й категор╕╖
Bucket_DisabledGlobally                 Глобально заборонено
Bucket_To                               до
Bucket_Quarantine                       Карантин

SingleBucket_Title                      Подробиц╕ для %s
SingleBucket_WordCount                  К╕льк╕сть сл╕в в категор╕╖
SingleBucket_TotalWordCount             Загальна к╕льк╕сть сл╕в
SingleBucket_Percentage                 В╕дсоток в╕д всього
SingleBucket_WordTable                  Таблиця сл╕в для %s
SingleBucket_Message1                   Слова з з╕рочками (*) використовувалися при класиф╕кац╕╖ в ц╕й POPFile сес╕╖.  Клацн╕ть по слову, щоб побачити його в╕рог╕дн╕сть у вс╕х категор╕ях.
SingleBucket_Unique                     %s ун╕кальне
SingleBucket_ClearBucket                Вилучити вс╕ слова

Session_Title                           POPFile сес╕я зак╕нчилася
Session_Error                           Ваша сес╕я POPFile зак╕нчилася. Це могло трапитися при зупинц╕ та запуску POPFile але при в╕дкритому переглядач╕.  Клацн╕ть на одному з посилань вгор╕ щоб продовжити роботу з POPFile.

View_Title                              Перегляд одного пов╕домлення

Header_MenuSummary                      Ця таблиця - це нав╕гац╕йне меню, що нада╓ доступ до кожно╖ з р╕зних стор╕нок центру управл╕ння.
History_MainTableSummary                Ця таблиця показу╓ автора та тему щойно прийнятих пов╕домлень та дозволя╓ ╖х переглянути та перекласиф╕кувати.  Клацнувши на тем╕ ви отрима╓те повний текст пов╕домлення, разом з ╕нформац╕╓ю, чому його так було прокласиф╕ковано. Стовпець 'Ма╓ бути' дозволя╓ Вам вказати, як╕й категор╕╖ належить пов╕домлення, або в╕дм╕нити ту зм╕ну. Стовпець 'Вилучити' дозволя╓ вилучити певне пов╕домлення з ╕стор╕╖ якщо ви ╖х б╕льше не потребу╓те.
History_OpenMessageSummary              Ця таблиця м╕стить повний текст пов╕домлення, з словами що використовуються для класиф╕кац╕╖ п╕дсв╕чен╕ у в╕дпов╕дност╕ до категор╕╖ найв╕дпов╕дн╕ш╕й кожному.
Bucket_MainTableSummary                 Ця таблиця забезпечу╓ огляд категор╕й класиф╕кац╕╖.  Кожен рядок показу╓ ╕м'я категор╕╖, загальну к╕льк╕сть сл╕в для т╕╓╖ категор╕╖, поточну к╕льк╕сть ун╕кальних сл╕в в кожн╕й категор╕╖, признак того, ячи буде модиф╕куватися тема пов╕домлення при класиф╕кац╕╖ в ту категор╕ю, чи проводити карантин пов╕домленням отриманим в ту категор╕ю, ╕ таблицю для вибору кольору, який використову╓ться при в╕дображенн╕ будь-чого що стосу╓ться то╖ категор╕╖ в центр╕ управл╕ння.
Bucket_StatisticsTableSummary           Ця таблиця забезпечу╓ три блоки статистики загально╖ ефективност╕ POPFile.  Перший, ╓ про те, наск╕льки точною ╓ класиф╕кац╕я, другий - про те, ск╕льки пов╕домлень прокласиф╕ковано, ╕ в як╕ категор╕╖, ╕ трет╕й - ск╕льки сл╕в ╓ в кожн╕й категор╕╖, та яка ╖х процентна доля.
Bucket_MaintenanceTableSummary          Ця таблиця м╕стить форми, що дозволяють створювати, знищувати та перейменовувати категор╕╖, ╕ шукати слово у вс╕х категор╕ях, щоб побачити його в╕дносну ╕мов╕рн╕сть.
Bucket_AccuracyChartSummary             Ця таблиця граф╕чно в╕добража╓ точн╕сть класиф╕кац╕╖ пов╕домлень
Bucket_BarChartSummary                  Ця таблиця граф╕чно в╕добража╓ в╕дсоткову долю кожно╖ окремо╖ категор╕╖.  Вона використову╓ться ╕ для загально╖ к╕лькост╕ пов╕домлень, ╕ загально╖ к╕лькост╕ сл╕в.
Bucket_LookupResultsSummary             Ця таблиця показу╓ ╕мов╕рност╕ асоц╕йован╕ з кожножним окремим словом з сукупност╕.  Для кожно╖ категор╕╖, в╕на показу╓ частоту з якою з'явля╓ться те слово, ╕мов╕рн╕сть, що воно трапиться в т╕й категор╕╖, та загальний вплив на бали категор╕╖, якби слово ╕снувало в пов╕домленн╕.
Bucket_WordListTableSummary             Ця таблиця забезпечу╓ список ус╕х сл╕в для певно╖ категор╕╖, згрупован╕ по перш╕й л╕тер╕ в кожному рядку.
Magnet_MainTableSummary                 Ця таблиця показу╓ список магн╕т╕в що використовуються для автоматично╖ класиф╕кац╕╖ пов╕домлення зг╕дно встановлених правил. Кожен рядок показу╓ як визначено магн╕т, яка категор╕я йому призначена, та кнопка, щоб знищити магн╕т.
Configuration_MainTableSummary          Ця таблиця м╕стить к╕лька форм що дозволяють вам контролювати конф╕гурац╕ю POPFile.
Configuration_InsertionTableSummary     Ця таблиця м╕стить кнопки що визначають як╕ модиф╕кац╕╖ зд╕йснюються над заголовками чи темою пов╕домлення перед тим, як воно переда╓ться до поштового кл╕╓нта.
Security_MainTableSummary               Ця таблиця забезпечу╓ наб╕р параметр╕в, як╕ впливають на безпеку ус╕╓╖ конф╕гурац╕╖ POPFile, чи в╕н повинен автоматично перев╕ряти за оновленнями програми, ╕ чи в╕дсилати статистику про ефективн╕сть POPFile в центральну базу даних автора програми задля загально╖ ╕нформац╕╖.
Advanced_MainTableSummary               Ця таблиця забезпечу╓ список сл╕в, як╕ POPFile ╕гнору╓ при класиф╕кац╕╖ пов╕домлення через ╖х в╕дносну частоту в пов╕домленн╕ взагал╕.  Вони з╕бран╕ в ряди по перш╕й л╕тер╕ сл╕в.

